### ISSUE TITLE
Chrome extension version 1

### ISSUE THREAD

**Issue by Livshitz** [feedox/savee#9]
- [x] Inject JS & CSS into visited page
- [x] Connection to the feedex API
- [x] Getting the text from the context menu
- [x] Sending the text from background.js to content.js
- [x] Auto paste into reply section
- [x] Added animation while loading
- [x] Sending the request to the Google Chrome store

**Comment by Orkessler** [comment]
Right now we get the selection text by chrome context menu and we can log it to console but we still dont use it to get the response and  inject it into visited page

**Comment by Orkessler** [comment]
Version #1 is finished
